<a href="https://colab.research.google.com/github/omprakashatale/OJT_Assignemnt/blob/main/Q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A = np.array([[5, 8, 9, 5, 0],
              [0, 1, 7, 6, 9],
              [2, 4, 5, 2, 4],
              [2, 4, 7, 7, 9],
              [1, 7, 0, 6, 9]], dtype=float)
print("Original Matrix A:")
print(A)
rows, cols = A.shape
for i in range(min(rows, cols)):
    pivot_row = i
    while pivot_row < rows and A[pivot_row, i] == 0:
        pivot_row += 1

    if pivot_row == rows:
        continue
    A[[i, pivot_row]] = A[[pivot_row, i]]

    A[i] /= A[i, i]

    for j in range(i + 1, rows):
        A[j] -= A[j, i] * A[i]

print("\nRow Echelon Form of Matrix A:")
print(A)

Original Matrix A:
[[5. 8. 9. 5. 0.]
 [0. 1. 7. 6. 9.]
 [2. 4. 5. 2. 4.]
 [2. 4. 7. 7. 9.]
 [1. 7. 0. 6. 9.]]

Row Echelon Form of Matrix A:
[[ 1.          1.6         1.8         1.          0.        ]
 [ 0.          1.          7.          6.          9.        ]
 [-0.         -0.          1.          1.14285714  0.76190476]
 [ 0.          0.          0.          1.          1.28070175]
 [-0.         -0.         -0.         -0.          1.        ]]
