In [ ]:
#Q3
import numpy as np
A = np.array([[5, 8, 9, 5, 0],
              [0, 1, 7, 6, 9],
              [2, 4, 5, 2, 4],
              [2, 4, 7, 7, 9],
              [1, 7, 0, 6, 9]], dtype=float)
U, S, Vt = np.linalg.svd(A)
Sigma = np.diag(S)
reconstructed_A = np.dot(U, np.dot(Sigma, Vt))
print("Matrix U:")
print(U)
print("\nMatrix Σ:")
print(Sigma)
print("\nMatrix V^T:")
print(Vt)
print("\nIs A equal to U * Σ * V^T?")
print(np.allclose(A, reconstructed_A))


Matrix U:
[[-0.43689897  0.83058378 -0.13125236  0.27232378 -0.1669205 ]
 [-0.4700234  -0.31059166  0.58397429  0.12469234 -0.57099621]
 [-0.30524405  0.14764731  0.01865437 -0.94044831 -0.01534021]
 [-0.55156434 -0.14864436  0.20839702  0.14709456  0.78013813]
 [-0.43680675 -0.41202977 -0.7732849   0.06489791 -0.19300273]]

Matrix Σ:
[[25.28145148  0.          0.          0.          0.        ]
 [ 0.         10.21162074  0.          0.          0.        ]
 [ 0.          0.          6.75929996  0.          0.        ]
 [ 0.          0.          0.          1.88976353  0.        ]
 [ 0.          0.          0.          0.          0.55827467]]

Matrix V^T:
[[-0.17146636 -0.41335032 -0.49876192 -0.4784897  -0.56747243]
 [ 0.3661412   0.33744712  0.48952449 -0.09087936 -0.71005407]
 [-0.14431138 -0.73540653  0.65962449 -0.04379707  0.03645277]
 [-0.0847676  -0.22005245 -0.18458357  0.87202745 -0.38715425]
 [ 0.89918218 -0.35500016 -0.20597756  0.02094019  0.15026992]]

Is A equal to U *

In [ ]:
import numpy as np
A = np.array([[5, 8, 9, 5, 0],
              [0, 1, 7, 6, 9],
              [2, 4, 5, 2, 4],
              [2, 4, 7, 7, 9],
              [1, 7, 0, 6, 9]], dtype=float)
U, S, Vt = np.linalg.svd(A)
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(S[:2]), Vt[:2, :]))
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(S[:3]), Vt[:3, :]))
print("Rank-2 Approximation:")
print(rank_2_approximation)
print("\nRank-3 Approximation:")
print(rank_3_approximation)



Rank-2 Approximation:
[[4.99938695 7.42772986 9.66099901 4.51432639 0.24558347]
 [0.87624348 3.84152746 4.3741274  5.97406978 8.99524213]
 [1.87524585 3.69860485 4.58701709 3.55549065 3.30863039]
 [1.83522076 5.25168941 6.21186019 6.81017234 8.9908235 ]
 [0.35298555 3.1448665  3.44821178 5.66638796 9.25420632]]

Rank-3 Approximation:
[[5.12741627e+00 8.08016348e+00 9.07579726e+00 4.55318202e+00
  2.13243514e-01]
 [3.06609305e-01 9.38688581e-01 6.97783506e+00 5.80119146e+00
  9.13913060e+00]
 [1.85704955e+00 3.60587706e+00 4.67018948e+00 3.54996825e+00
  3.31322674e+00]
 [1.63194115e+00 4.21578255e+00 7.14101911e+00 6.74847899e+00
  9.04217153e+00]
 [1.10728161e+00 6.98873686e+00 4.43862316e-04 5.89530934e+00
  9.06367262e+00]]
